// Code generated by tygo. DO NOT EDIT.

//////////
// source: api.go

export type APIVersion = number /* int */;
export const APIVersionAlpha: APIVersion = 0;
export type APIEncoding = number /* int */;
export const APIEncodingJSON: APIEncoding = 0;

//////////
// source: config.go

export interface ConfigSchema {
  sections: ConfigSectionSchema[];
  fields: ConfigFieldSchema[];
}
export interface ConfigSectionSchema {
  name: string;
  description: string;
  fields: ConfigFieldSchema[];
}
export type ConfigFieldType = string;
export const ConfigFieldTypeString: ConfigFieldType = "STRING";
export const ConfigFieldTypeInt: ConfigFieldType = "INT";
export const ConfigFieldTypeFloat: ConfigFieldType = "FLOAT";
export const ConfigFieldTypeBool: ConfigFieldType = "BOOL";
export interface ConfigFieldSchema {
  name: string;
  description: string;
  key: string;
  type: ConfigFieldType;
  required: boolean;
  default_value: any;
}

//////////
// source: discord.go

export interface DiscordCommand {
  type?: any /* distype.ApplicationCommandType */;
  name: string;
  name_localizations?: { [key: string]: string};
  description: string;
  description_localizations?: { [key: string]: string};
  options?: DiscordCommandOption[];
  default_member_permissions: string;
  dm_permission?: boolean;
  nsfw?: boolean;
}
export interface DiscordCommandOption {
  type: any /* distype.ApplicationCommandOptionType */;
  name: string;
  name_locations?: { [key: string]: string};
  description: string;
  description_locations?: { [key: string]: string};
  required?: boolean;
  choices?: DiscordCommandOptionChoice[];
  options?: DiscordCommandOption[];
  channel_types?: any /* distype.ChannelType */[];
  min_value?: number /* int */;
  max_value?: number /* int */;
  min_length?: number /* int */;
  max_length?: number /* int */;
  autocomplete?: boolean;
}
export interface DiscordCommandOptionChoice {
  name: string;
  name_localizations?: { [key: string]: string};
  value: any;
}

//////////
// source: manifest.go

export interface Manifest {
  events: string[];
  discord_commands: DiscordCommand[];
  config_schema: ConfigSchema;
}
