// Code generated by tygo. DO NOT EDIT.

//////////
// source: data.go

export interface MessageData {
  content?: string;
  flags?: number /* int */;
  embeds?: EmbedData[];
}
export interface EmbedData {
  title?: string;
  description?: string;
  url?: string;
  timestamp?: string /* RFC3339 */;
  color?: number /* int */;
  footer?: EmbedFooterData;
  image?: EmbedImageData;
  thumbnail?: EmbedThumbnailData;
  author?: EmbedAuthorData;
  fields?: EmbedFieldData[];
}
export interface EmbedFooterData {
  text?: string;
  icon_url?: string;
}
export interface EmbedImageData {
  url?: string;
}
export interface EmbedThumbnailData {
  url?: string;
}
export interface EmbedAuthorData {
  name?: string;
  url?: string;
  icon_url?: string;
}
export interface EmbedFieldData {
  name?: string;
  value?: string;
  inline?: boolean;
}
