// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_integrations.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAppIntegrations = `-- name: GetAppIntegrations :many
SELECT app_id, integration_id, enabled, created_at, updated_at FROM app_integrations WHERE app_id = $1 ORDER BY integration_id
`

func (q *Queries) GetAppIntegrations(ctx context.Context, appID string) ([]AppIntegration, error) {
	rows, err := q.db.Query(ctx, getAppIntegrations, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppIntegration
	for rows.Next() {
		var i AppIntegration
		if err := rows.Scan(
			&i.AppID,
			&i.IntegrationID,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAppIntegrationEnabled = `-- name: SetAppIntegrationEnabled :one
INSERT INTO app_integrations (
    app_id,
    integration_id,
    enabled,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (app_id, integration_id) DO UPDATE SET
    enabled = EXCLUDED.enabled,
    updated_at = EXCLUDED.updated_at
RETURNING app_id, integration_id, enabled, created_at, updated_at
`

type SetAppIntegrationEnabledParams struct {
	AppID         string
	IntegrationID string
	Enabled       bool
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

func (q *Queries) SetAppIntegrationEnabled(ctx context.Context, arg SetAppIntegrationEnabledParams) (AppIntegration, error) {
	row := q.db.QueryRow(ctx, setAppIntegrationEnabled,
		arg.AppID,
		arg.IntegrationID,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AppIntegration
	err := row.Scan(
		&i.AppID,
		&i.IntegrationID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
