// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: deployment_metrics.sql

package pgmodel

import (
	"context"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const createDeploymentMetricEntry = `-- name: CreateDeploymentMetricEntry :exec
INSERT INTO deployment_metrics (
    deployment_id,
    type,
    metadata,
    event_id,
    event_type,
    event_success,
    event_execution_time,
    event_total_time,
    call_type,
    call_success,
    call_total_time,
    timestamp
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
`

type CreateDeploymentMetricEntryParams struct {
	DeploymentID       string
	Type               string
	Metadata           pqtype.NullRawMessage
	EventID            int64
	EventType          string
	EventSuccess       bool
	EventExecutionTime int32
	EventTotalTime     int32
	CallType           string
	CallSuccess        bool
	CallTotalTime      int32
	Timestamp          time.Time
}

func (q *Queries) CreateDeploymentMetricEntry(ctx context.Context, arg CreateDeploymentMetricEntryParams) error {
	_, err := q.db.ExecContext(ctx, createDeploymentMetricEntry,
		arg.DeploymentID,
		arg.Type,
		arg.Metadata,
		arg.EventID,
		arg.EventType,
		arg.EventSuccess,
		arg.EventExecutionTime,
		arg.EventTotalTime,
		arg.CallType,
		arg.CallSuccess,
		arg.CallTotalTime,
		arg.Timestamp,
	)
	return err
}
