// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: entitlements.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEntitlements = `-- name: GetEntitlements :many
SELECT id, type, subscription_id, app_id, feature_usage_credits_per_month, feature_max_collaborator, created_at, updated_at, ends_at FROM entitlements WHERE app_id = $1
`

func (q *Queries) GetEntitlements(ctx context.Context, appID string) ([]Entitlement, error) {
	rows, err := q.db.Query(ctx, getEntitlements, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entitlement
	for rows.Next() {
		var i Entitlement
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.SubscriptionID,
			&i.AppID,
			&i.FeatureUsageCreditsPerMonth,
			&i.FeatureMaxCollaborator,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscriptionEntitlement = `-- name: UpdateSubscriptionEntitlement :one
UPDATE entitlements SET
    feature_usage_credits_per_month = $2,
    feature_max_collaborator = $3,
    updated_at = $4,
    ends_at = $5
WHERE subscription_id = $1 RETURNING id, type, subscription_id, app_id, feature_usage_credits_per_month, feature_max_collaborator, created_at, updated_at, ends_at
`

type UpdateSubscriptionEntitlementParams struct {
	SubscriptionID              pgtype.Text
	FeatureUsageCreditsPerMonth int32
	FeatureMaxCollaborator      int32
	UpdatedAt                   pgtype.Timestamp
	EndsAt                      pgtype.Timestamp
}

func (q *Queries) UpdateSubscriptionEntitlement(ctx context.Context, arg UpdateSubscriptionEntitlementParams) (Entitlement, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionEntitlement,
		arg.SubscriptionID,
		arg.FeatureUsageCreditsPerMonth,
		arg.FeatureMaxCollaborator,
		arg.UpdatedAt,
		arg.EndsAt,
	)
	var i Entitlement
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.SubscriptionID,
		&i.AppID,
		&i.FeatureUsageCreditsPerMonth,
		&i.FeatureMaxCollaborator,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndsAt,
	)
	return i, err
}

const upsertSubscriptionEntitlement = `-- name: UpsertSubscriptionEntitlement :one
INSERT INTO entitlements (
    id,
    type,
    subscription_id,
    app_id,
    feature_usage_credits_per_month,
    feature_max_collaborator,
    created_at,
    updated_at,
    ends_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) 
ON CONFLICT (subscription_id) DO UPDATE SET 
    feature_usage_credits_per_month = EXCLUDED.feature_usage_credits_per_month,
    feature_max_collaborator = EXCLUDED.feature_max_collaborator,
    updated_at = EXCLUDED.updated_at,
    ends_at = EXCLUDED.ends_at
RETURNING id, type, subscription_id, app_id, feature_usage_credits_per_month, feature_max_collaborator, created_at, updated_at, ends_at
`

type UpsertSubscriptionEntitlementParams struct {
	ID                          string
	Type                        string
	SubscriptionID              pgtype.Text
	AppID                       string
	FeatureUsageCreditsPerMonth int32
	FeatureMaxCollaborator      int32
	CreatedAt                   pgtype.Timestamp
	UpdatedAt                   pgtype.Timestamp
	EndsAt                      pgtype.Timestamp
}

func (q *Queries) UpsertSubscriptionEntitlement(ctx context.Context, arg UpsertSubscriptionEntitlementParams) (Entitlement, error) {
	row := q.db.QueryRow(ctx, upsertSubscriptionEntitlement,
		arg.ID,
		arg.Type,
		arg.SubscriptionID,
		arg.AppID,
		arg.FeatureUsageCreditsPerMonth,
		arg.FeatureMaxCollaborator,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.EndsAt,
	)
	var i Entitlement
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.SubscriptionID,
		&i.AppID,
		&i.FeatureUsageCreditsPerMonth,
		&i.FeatureMaxCollaborator,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndsAt,
	)
	return i, err
}
