// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flow_versions.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFlowVersionsByCommand = `-- name: CountFlowVersionsByCommand :one
SELECT COUNT(*) FROM flow_versions WHERE command_id = $1
`

func (q *Queries) CountFlowVersionsByCommand(ctx context.Context, commandID pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countFlowVersionsByCommand, commandID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFlowVersionsByEventListener = `-- name: CountFlowVersionsByEventListener :one
SELECT COUNT(*) FROM flow_versions WHERE event_listener_id = $1
`

func (q *Queries) CountFlowVersionsByEventListener(ctx context.Context, eventListenerID pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countFlowVersionsByEventListener, eventListenerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFlowVersion = `-- name: CreateFlowVersion :exec
INSERT INTO flow_versions (
    id,
    app_id,
    command_id,
    event_listener_id,
    flow_source,
    auto_saved,
    creator_user_id,
    created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateFlowVersionParams struct {
	ID              string
	AppID           string
	CommandID       pgtype.Text
	EventListenerID pgtype.Text
	FlowSource      []byte
	AutoSaved       bool
	CreatorUserID   pgtype.Text
	CreatedAt       pgtype.Timestamp
}

func (q *Queries) CreateFlowVersion(ctx context.Context, arg CreateFlowVersionParams) error {
	_, err := q.db.Exec(ctx, createFlowVersion,
		arg.ID,
		arg.AppID,
		arg.CommandID,
		arg.EventListenerID,
		arg.FlowSource,
		arg.AutoSaved,
		arg.CreatorUserID,
		arg.CreatedAt,
	)
	return err
}

const deleteOldFlowVersionsByCommand = `-- name: DeleteOldFlowVersionsByCommand :exec
DELETE FROM flow_versions old WHERE old.command_id = $1 AND old.id NOT IN (
    SELECT kept.id FROM flow_versions kept
    WHERE kept.command_id = $1
    ORDER BY kept.created_at DESC
    LIMIT $2
)
`

type DeleteOldFlowVersionsByCommandParams struct {
	CommandID pgtype.Text
	KeepCount int32
}

func (q *Queries) DeleteOldFlowVersionsByCommand(ctx context.Context, arg DeleteOldFlowVersionsByCommandParams) error {
	_, err := q.db.Exec(ctx, deleteOldFlowVersionsByCommand, arg.CommandID, arg.KeepCount)
	return err
}

const deleteOldFlowVersionsByEventListener = `-- name: DeleteOldFlowVersionsByEventListener :exec
DELETE FROM flow_versions old WHERE old.event_listener_id = $1 AND old.id NOT IN (
    SELECT kept.id FROM flow_versions kept
    WHERE kept.event_listener_id = $1
    ORDER BY kept.created_at DESC
    LIMIT $2
)
`

type DeleteOldFlowVersionsByEventListenerParams struct {
	EventListenerID pgtype.Text
	KeepCount       int32
}

func (q *Queries) DeleteOldFlowVersionsByEventListener(ctx context.Context, arg DeleteOldFlowVersionsByEventListenerParams) error {
	_, err := q.db.Exec(ctx, deleteOldFlowVersionsByEventListener, arg.EventListenerID, arg.KeepCount)
	return err
}

const getFlowVersion = `-- name: GetFlowVersion :one
SELECT id, app_id, command_id, event_listener_id, flow_source, auto_saved, creator_user_id, created_at FROM flow_versions WHERE id = $1 AND app_id = $2
`

type GetFlowVersionParams struct {
	ID    string
	AppID string
}

func (q *Queries) GetFlowVersion(ctx context.Context, arg GetFlowVersionParams) (FlowVersion, error) {
	row := q.db.QueryRow(ctx, getFlowVersion, arg.ID, arg.AppID)
	var i FlowVersion
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.CommandID,
		&i.EventListenerID,
		&i.FlowSource,
		&i.AutoSaved,
		&i.CreatorUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getFlowVersionsByCommand = `-- name: GetFlowVersionsByCommand :many
SELECT
    flow_versions.id,
    flow_versions.app_id,
    flow_versions.command_id,
    flow_versions.event_listener_id,
    flow_versions.auto_saved,
    flow_versions.creator_user_id,
    flow_versions.created_at,
    users.display_name AS creator_display_name
FROM flow_versions
LEFT JOIN users ON users.id = flow_versions.creator_user_id
WHERE flow_versions.app_id = $1 AND flow_versions.command_id = $2
ORDER BY flow_versions.created_at DESC
LIMIT $3
`

type GetFlowVersionsByCommandParams struct {
	AppID     string
	CommandID pgtype.Text
	MaxCount  int32
}

type GetFlowVersionsByCommandRow struct {
	ID                 string
	AppID              string
	CommandID          pgtype.Text
	EventListenerID    pgtype.Text
	AutoSaved          bool
	CreatorUserID      pgtype.Text
	CreatedAt          pgtype.Timestamp
	CreatorDisplayName pgtype.Text
}

// Leaves out the flow so the list stays small, it's loaded on restore.
func (q *Queries) GetFlowVersionsByCommand(ctx context.Context, arg GetFlowVersionsByCommandParams) ([]GetFlowVersionsByCommandRow, error) {
	rows, err := q.db.Query(ctx, getFlowVersionsByCommand, arg.AppID, arg.CommandID, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFlowVersionsByCommandRow
	for rows.Next() {
		var i GetFlowVersionsByCommandRow
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.CommandID,
			&i.EventListenerID,
			&i.AutoSaved,
			&i.CreatorUserID,
			&i.CreatedAt,
			&i.CreatorDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowVersionsByEventListener = `-- name: GetFlowVersionsByEventListener :many
SELECT
    flow_versions.id,
    flow_versions.app_id,
    flow_versions.command_id,
    flow_versions.event_listener_id,
    flow_versions.auto_saved,
    flow_versions.creator_user_id,
    flow_versions.created_at,
    users.display_name AS creator_display_name
FROM flow_versions
LEFT JOIN users ON users.id = flow_versions.creator_user_id
WHERE flow_versions.app_id = $1 AND flow_versions.event_listener_id = $2
ORDER BY flow_versions.created_at DESC
LIMIT $3
`

type GetFlowVersionsByEventListenerParams struct {
	AppID           string
	EventListenerID pgtype.Text
	MaxCount        int32
}

type GetFlowVersionsByEventListenerRow struct {
	ID                 string
	AppID              string
	CommandID          pgtype.Text
	EventListenerID    pgtype.Text
	AutoSaved          bool
	CreatorUserID      pgtype.Text
	CreatedAt          pgtype.Timestamp
	CreatorDisplayName pgtype.Text
}

func (q *Queries) GetFlowVersionsByEventListener(ctx context.Context, arg GetFlowVersionsByEventListenerParams) ([]GetFlowVersionsByEventListenerRow, error) {
	rows, err := q.db.Query(ctx, getFlowVersionsByEventListener, arg.AppID, arg.EventListenerID, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFlowVersionsByEventListenerRow
	for rows.Next() {
		var i GetFlowVersionsByEventListenerRow
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.CommandID,
			&i.EventListenerID,
			&i.AutoSaved,
			&i.CreatorUserID,
			&i.CreatedAt,
			&i.CreatorDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
