// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: marketplace.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMarketplaceListingsByAuthor = `-- name: CountMarketplaceListingsByAuthor :one
SELECT COUNT(*) FROM marketplace_listings WHERE author_user_id = $1
`

func (q *Queries) CountMarketplaceListingsByAuthor(ctx context.Context, authorUserID string) (int64, error) {
	row := q.db.QueryRow(ctx, countMarketplaceListingsByAuthor, authorUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenMarketplaceReportsByListing = `-- name: CountOpenMarketplaceReportsByListing :one
SELECT COUNT(*) FROM marketplace_reports WHERE listing_id = $1 AND resolved_at IS NULL
`

func (q *Queries) CountOpenMarketplaceReportsByListing(ctx context.Context, listingID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenMarketplaceReportsByListing, listingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMarketplaceListing = `-- name: CreateMarketplaceListing :one
INSERT INTO marketplace_listings (
    id,
    name,
    description,
    author_user_id,
    source_app_id,
    status,
    items,
    command_count,
    event_listener_count,
    block_types,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) RETURNING id, name, description, author_user_id, source_app_id, status, items, command_count, event_listener_count, block_types, import_count, review_note, reviewed_by_user_id, reviewed_at, created_at, updated_at
`

type CreateMarketplaceListingParams struct {
	ID                 string
	Name               string
	Description        string
	AuthorUserID       string
	SourceAppID        pgtype.Text
	Status             string
	Items              []byte
	CommandCount       int32
	EventListenerCount int32
	BlockTypes         []string
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
}

func (q *Queries) CreateMarketplaceListing(ctx context.Context, arg CreateMarketplaceListingParams) (MarketplaceListing, error) {
	row := q.db.QueryRow(ctx, createMarketplaceListing,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.AuthorUserID,
		arg.SourceAppID,
		arg.Status,
		arg.Items,
		arg.CommandCount,
		arg.EventListenerCount,
		arg.BlockTypes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i MarketplaceListing
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AuthorUserID,
		&i.SourceAppID,
		&i.Status,
		&i.Items,
		&i.CommandCount,
		&i.EventListenerCount,
		&i.BlockTypes,
		&i.ImportCount,
		&i.ReviewNote,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMarketplaceModerator = `-- name: CreateMarketplaceModerator :one
INSERT INTO marketplace_moderators (
    discord_user_id,
    added_by_user_id,
    created_at
) VALUES ($1, $2, $3)
ON CONFLICT (discord_user_id) DO UPDATE SET discord_user_id = EXCLUDED.discord_user_id
RETURNING discord_user_id, added_by_user_id, created_at
`

type CreateMarketplaceModeratorParams struct {
	DiscordUserID string
	AddedByUserID pgtype.Text
	CreatedAt     pgtype.Timestamp
}

func (q *Queries) CreateMarketplaceModerator(ctx context.Context, arg CreateMarketplaceModeratorParams) (MarketplaceModerator, error) {
	row := q.db.QueryRow(ctx, createMarketplaceModerator, arg.DiscordUserID, arg.AddedByUserID, arg.CreatedAt)
	var i MarketplaceModerator
	err := row.Scan(&i.DiscordUserID, &i.AddedByUserID, &i.CreatedAt)
	return i, err
}

const createMarketplaceReport = `-- name: CreateMarketplaceReport :one
INSERT INTO marketplace_reports (
    id,
    listing_id,
    reporter_user_id,
    reason,
    created_at
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (listing_id, reporter_user_id) WHERE resolved_at IS NULL DO UPDATE SET reason = EXCLUDED.reason
RETURNING id, listing_id, reporter_user_id, reason, created_at, resolved_at, resolved_by_user_id
`

type CreateMarketplaceReportParams struct {
	ID             string
	ListingID      string
	ReporterUserID string
	Reason         string
	CreatedAt      pgtype.Timestamp
}

func (q *Queries) CreateMarketplaceReport(ctx context.Context, arg CreateMarketplaceReportParams) (MarketplaceReport, error) {
	row := q.db.QueryRow(ctx, createMarketplaceReport,
		arg.ID,
		arg.ListingID,
		arg.ReporterUserID,
		arg.Reason,
		arg.CreatedAt,
	)
	var i MarketplaceReport
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.ReporterUserID,
		&i.Reason,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ResolvedByUserID,
	)
	return i, err
}

const deleteMarketplaceListing = `-- name: DeleteMarketplaceListing :exec
DELETE FROM marketplace_listings WHERE id = $1
`

func (q *Queries) DeleteMarketplaceListing(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMarketplaceListing, id)
	return err
}

const deleteMarketplaceModerator = `-- name: DeleteMarketplaceModerator :exec
DELETE FROM marketplace_moderators WHERE discord_user_id = $1
`

func (q *Queries) DeleteMarketplaceModerator(ctx context.Context, discordUserID string) error {
	_, err := q.db.Exec(ctx, deleteMarketplaceModerator, discordUserID)
	return err
}

const incrementMarketplaceListingImportCount = `-- name: IncrementMarketplaceListingImportCount :exec
UPDATE marketplace_listings SET import_count = import_count + 1 WHERE id = $1
`

func (q *Queries) IncrementMarketplaceListingImportCount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementMarketplaceListingImportCount, id)
	return err
}

const marketplaceListing = `-- name: MarketplaceListing :one
SELECT marketplace_listings.id, marketplace_listings.name, marketplace_listings.description, marketplace_listings.author_user_id, marketplace_listings.source_app_id, marketplace_listings.status, marketplace_listings.items, marketplace_listings.command_count, marketplace_listings.event_listener_count, marketplace_listings.block_types, marketplace_listings.import_count, marketplace_listings.review_note, marketplace_listings.reviewed_by_user_id, marketplace_listings.reviewed_at, marketplace_listings.created_at, marketplace_listings.updated_at, users.id, users.email, users.display_name, users.discord_id, users.discord_username, users.discord_avatar, users.created_at, users.updated_at
FROM marketplace_listings
JOIN users ON users.id = marketplace_listings.author_user_id
WHERE marketplace_listings.id = $1
`

type MarketplaceListingRow struct {
	MarketplaceListing MarketplaceListing
	User               User
}

func (q *Queries) MarketplaceListing(ctx context.Context, id string) (MarketplaceListingRow, error) {
	row := q.db.QueryRow(ctx, marketplaceListing, id)
	var i MarketplaceListingRow
	err := row.Scan(
		&i.MarketplaceListing.ID,
		&i.MarketplaceListing.Name,
		&i.MarketplaceListing.Description,
		&i.MarketplaceListing.AuthorUserID,
		&i.MarketplaceListing.SourceAppID,
		&i.MarketplaceListing.Status,
		&i.MarketplaceListing.Items,
		&i.MarketplaceListing.CommandCount,
		&i.MarketplaceListing.EventListenerCount,
		&i.MarketplaceListing.BlockTypes,
		&i.MarketplaceListing.ImportCount,
		&i.MarketplaceListing.ReviewNote,
		&i.MarketplaceListing.ReviewedByUserID,
		&i.MarketplaceListing.ReviewedAt,
		&i.MarketplaceListing.CreatedAt,
		&i.MarketplaceListing.UpdatedAt,
		&i.User.ID,
		&i.User.Email,
		&i.User.DisplayName,
		&i.User.DiscordID,
		&i.User.DiscordUsername,
		&i.User.DiscordAvatar,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const marketplaceListings = `-- name: MarketplaceListings :many
SELECT marketplace_listings.id, marketplace_listings.name, marketplace_listings.description, marketplace_listings.author_user_id, marketplace_listings.source_app_id, marketplace_listings.status, marketplace_listings.items, marketplace_listings.command_count, marketplace_listings.event_listener_count, marketplace_listings.block_types, marketplace_listings.import_count, marketplace_listings.review_note, marketplace_listings.reviewed_by_user_id, marketplace_listings.reviewed_at, marketplace_listings.created_at, marketplace_listings.updated_at, users.id, users.email, users.display_name, users.discord_id, users.discord_username, users.discord_avatar, users.created_at, users.updated_at
FROM marketplace_listings
JOIN users ON users.id = marketplace_listings.author_user_id
WHERE marketplace_listings.status = $1
    AND (
        $2::TEXT IS NULL
        OR marketplace_listings.name ILIKE '%' || $2::TEXT || '%'
        OR marketplace_listings.description ILIKE '%' || $2::TEXT || '%'
    )
    AND (
        $3::TEXT = ''
        OR ($3::TEXT = 'command' AND marketplace_listings.command_count > 0 AND marketplace_listings.event_listener_count = 0)
        OR ($3::TEXT = 'event_listener' AND marketplace_listings.event_listener_count > 0 AND marketplace_listings.command_count = 0)
        OR ($3::TEXT = 'module' AND marketplace_listings.command_count + marketplace_listings.event_listener_count > 1)
    )
ORDER BY
    CASE WHEN $4::TEXT = 'popular' THEN marketplace_listings.import_count END DESC,
    marketplace_listings.updated_at DESC
LIMIT $6 OFFSET $5
`

type MarketplaceListingsParams struct {
	Status     string
	Search     pgtype.Text
	Kind       string
	Sort       string
	PageOffset int32
	PageLimit  int32
}

type MarketplaceListingsRow struct {
	MarketplaceListing MarketplaceListing
	User               User
}

// Search matches the name and description, the sort is by imports or by age.
func (q *Queries) MarketplaceListings(ctx context.Context, arg MarketplaceListingsParams) ([]MarketplaceListingsRow, error) {
	rows, err := q.db.Query(ctx, marketplaceListings,
		arg.Status,
		arg.Search,
		arg.Kind,
		arg.Sort,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketplaceListingsRow
	for rows.Next() {
		var i MarketplaceListingsRow
		if err := rows.Scan(
			&i.MarketplaceListing.ID,
			&i.MarketplaceListing.Name,
			&i.MarketplaceListing.Description,
			&i.MarketplaceListing.AuthorUserID,
			&i.MarketplaceListing.SourceAppID,
			&i.MarketplaceListing.Status,
			&i.MarketplaceListing.Items,
			&i.MarketplaceListing.CommandCount,
			&i.MarketplaceListing.EventListenerCount,
			&i.MarketplaceListing.BlockTypes,
			&i.MarketplaceListing.ImportCount,
			&i.MarketplaceListing.ReviewNote,
			&i.MarketplaceListing.ReviewedByUserID,
			&i.MarketplaceListing.ReviewedAt,
			&i.MarketplaceListing.CreatedAt,
			&i.MarketplaceListing.UpdatedAt,
			&i.User.ID,
			&i.User.Email,
			&i.User.DisplayName,
			&i.User.DiscordID,
			&i.User.DiscordUsername,
			&i.User.DiscordAvatar,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marketplaceListingsByAuthor = `-- name: MarketplaceListingsByAuthor :many
SELECT marketplace_listings.id, marketplace_listings.name, marketplace_listings.description, marketplace_listings.author_user_id, marketplace_listings.source_app_id, marketplace_listings.status, marketplace_listings.items, marketplace_listings.command_count, marketplace_listings.event_listener_count, marketplace_listings.block_types, marketplace_listings.import_count, marketplace_listings.review_note, marketplace_listings.reviewed_by_user_id, marketplace_listings.reviewed_at, marketplace_listings.created_at, marketplace_listings.updated_at, users.id, users.email, users.display_name, users.discord_id, users.discord_username, users.discord_avatar, users.created_at, users.updated_at
FROM marketplace_listings
JOIN users ON users.id = marketplace_listings.author_user_id
WHERE marketplace_listings.author_user_id = $1
ORDER BY marketplace_listings.updated_at DESC
`

type MarketplaceListingsByAuthorRow struct {
	MarketplaceListing MarketplaceListing
	User               User
}

func (q *Queries) MarketplaceListingsByAuthor(ctx context.Context, authorUserID string) ([]MarketplaceListingsByAuthorRow, error) {
	rows, err := q.db.Query(ctx, marketplaceListingsByAuthor, authorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketplaceListingsByAuthorRow
	for rows.Next() {
		var i MarketplaceListingsByAuthorRow
		if err := rows.Scan(
			&i.MarketplaceListing.ID,
			&i.MarketplaceListing.Name,
			&i.MarketplaceListing.Description,
			&i.MarketplaceListing.AuthorUserID,
			&i.MarketplaceListing.SourceAppID,
			&i.MarketplaceListing.Status,
			&i.MarketplaceListing.Items,
			&i.MarketplaceListing.CommandCount,
			&i.MarketplaceListing.EventListenerCount,
			&i.MarketplaceListing.BlockTypes,
			&i.MarketplaceListing.ImportCount,
			&i.MarketplaceListing.ReviewNote,
			&i.MarketplaceListing.ReviewedByUserID,
			&i.MarketplaceListing.ReviewedAt,
			&i.MarketplaceListing.CreatedAt,
			&i.MarketplaceListing.UpdatedAt,
			&i.User.ID,
			&i.User.Email,
			&i.User.DisplayName,
			&i.User.DiscordID,
			&i.User.DiscordUsername,
			&i.User.DiscordAvatar,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marketplaceModerator = `-- name: MarketplaceModerator :one
SELECT discord_user_id, added_by_user_id, created_at FROM marketplace_moderators WHERE discord_user_id = $1
`

func (q *Queries) MarketplaceModerator(ctx context.Context, discordUserID string) (MarketplaceModerator, error) {
	row := q.db.QueryRow(ctx, marketplaceModerator, discordUserID)
	var i MarketplaceModerator
	err := row.Scan(&i.DiscordUserID, &i.AddedByUserID, &i.CreatedAt)
	return i, err
}

const marketplaceModerators = `-- name: MarketplaceModerators :many
SELECT discord_user_id, added_by_user_id, created_at FROM marketplace_moderators ORDER BY created_at ASC
`

func (q *Queries) MarketplaceModerators(ctx context.Context) ([]MarketplaceModerator, error) {
	rows, err := q.db.Query(ctx, marketplaceModerators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketplaceModerator
	for rows.Next() {
		var i MarketplaceModerator
		if err := rows.Scan(&i.DiscordUserID, &i.AddedByUserID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openMarketplaceReports = `-- name: OpenMarketplaceReports :many
SELECT marketplace_reports.id, marketplace_reports.listing_id, marketplace_reports.reporter_user_id, marketplace_reports.reason, marketplace_reports.created_at, marketplace_reports.resolved_at, marketplace_reports.resolved_by_user_id, users.id, users.email, users.display_name, users.discord_id, users.discord_username, users.discord_avatar, users.created_at, users.updated_at
FROM marketplace_reports
JOIN users ON users.id = marketplace_reports.reporter_user_id
WHERE marketplace_reports.resolved_at IS NULL
ORDER BY marketplace_reports.created_at ASC
LIMIT 100
`

type OpenMarketplaceReportsRow struct {
	MarketplaceReport MarketplaceReport
	User              User
}

func (q *Queries) OpenMarketplaceReports(ctx context.Context) ([]OpenMarketplaceReportsRow, error) {
	rows, err := q.db.Query(ctx, openMarketplaceReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpenMarketplaceReportsRow
	for rows.Next() {
		var i OpenMarketplaceReportsRow
		if err := rows.Scan(
			&i.MarketplaceReport.ID,
			&i.MarketplaceReport.ListingID,
			&i.MarketplaceReport.ReporterUserID,
			&i.MarketplaceReport.Reason,
			&i.MarketplaceReport.CreatedAt,
			&i.MarketplaceReport.ResolvedAt,
			&i.MarketplaceReport.ResolvedByUserID,
			&i.User.ID,
			&i.User.Email,
			&i.User.DisplayName,
			&i.User.DiscordID,
			&i.User.DiscordUsername,
			&i.User.DiscordAvatar,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveMarketplaceReport = `-- name: ResolveMarketplaceReport :exec
UPDATE marketplace_reports SET
    resolved_at = $1,
    resolved_by_user_id = $2
WHERE id = $3 AND resolved_at IS NULL
`

type ResolveMarketplaceReportParams struct {
	ResolvedAt       pgtype.Timestamp
	ResolvedByUserID pgtype.Text
	ID               string
}

func (q *Queries) ResolveMarketplaceReport(ctx context.Context, arg ResolveMarketplaceReportParams) error {
	_, err := q.db.Exec(ctx, resolveMarketplaceReport, arg.ResolvedAt, arg.ResolvedByUserID, arg.ID)
	return err
}

const resolveMarketplaceReportsByListing = `-- name: ResolveMarketplaceReportsByListing :exec
UPDATE marketplace_reports SET
    resolved_at = $1,
    resolved_by_user_id = $2
WHERE listing_id = $3 AND resolved_at IS NULL
`

type ResolveMarketplaceReportsByListingParams struct {
	ResolvedAt       pgtype.Timestamp
	ResolvedByUserID pgtype.Text
	ListingID        string
}

func (q *Queries) ResolveMarketplaceReportsByListing(ctx context.Context, arg ResolveMarketplaceReportsByListingParams) error {
	_, err := q.db.Exec(ctx, resolveMarketplaceReportsByListing, arg.ResolvedAt, arg.ResolvedByUserID, arg.ListingID)
	return err
}

const reviewMarketplaceListing = `-- name: ReviewMarketplaceListing :one
UPDATE marketplace_listings SET
    status = $1,
    review_note = $2,
    reviewed_by_user_id = $3,
    reviewed_at = $4
WHERE id = $5 RETURNING id, name, description, author_user_id, source_app_id, status, items, command_count, event_listener_count, block_types, import_count, review_note, reviewed_by_user_id, reviewed_at, created_at, updated_at
`

type ReviewMarketplaceListingParams struct {
	Status           string
	ReviewNote       pgtype.Text
	ReviewedByUserID pgtype.Text
	ReviewedAt       pgtype.Timestamp
	ID               string
}

func (q *Queries) ReviewMarketplaceListing(ctx context.Context, arg ReviewMarketplaceListingParams) (MarketplaceListing, error) {
	row := q.db.QueryRow(ctx, reviewMarketplaceListing,
		arg.Status,
		arg.ReviewNote,
		arg.ReviewedByUserID,
		arg.ReviewedAt,
		arg.ID,
	)
	var i MarketplaceListing
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AuthorUserID,
		&i.SourceAppID,
		&i.Status,
		&i.Items,
		&i.CommandCount,
		&i.EventListenerCount,
		&i.BlockTypes,
		&i.ImportCount,
		&i.ReviewNote,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMarketplaceListing = `-- name: UpdateMarketplaceListing :one
UPDATE marketplace_listings SET
    name = $2,
    description = $3,
    source_app_id = $4,
    items = $5,
    command_count = $6,
    event_listener_count = $7,
    block_types = $8,
    status = $9,
    review_note = NULL,
    reviewed_by_user_id = NULL,
    reviewed_at = NULL,
    updated_at = $10
WHERE id = $1 RETURNING id, name, description, author_user_id, source_app_id, status, items, command_count, event_listener_count, block_types, import_count, review_note, reviewed_by_user_id, reviewed_at, created_at, updated_at
`

type UpdateMarketplaceListingParams struct {
	ID                 string
	Name               string
	Description        string
	SourceAppID        pgtype.Text
	Items              []byte
	CommandCount       int32
	EventListenerCount int32
	BlockTypes         []string
	Status             string
	UpdatedAt          pgtype.Timestamp
}

// Any change sends the listing back to the moderation queue.
func (q *Queries) UpdateMarketplaceListing(ctx context.Context, arg UpdateMarketplaceListingParams) (MarketplaceListing, error) {
	row := q.db.QueryRow(ctx, updateMarketplaceListing,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.SourceAppID,
		arg.Items,
		arg.CommandCount,
		arg.EventListenerCount,
		arg.BlockTypes,
		arg.Status,
		arg.UpdatedAt,
	)
	var i MarketplaceListing
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AuthorUserID,
		&i.SourceAppID,
		&i.Status,
		&i.Items,
		&i.CommandCount,
		&i.EventListenerCount,
		&i.BlockTypes,
		&i.ImportCount,
		&i.ReviewNote,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
