// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pgmodel

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type App struct {
	ID            string
	Name          string
	Description   pgtype.Text
	Enabled       bool
	OwnerUserID   string
	CreatorUserID string
	DiscordToken  string
	DiscordID     string
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type Collaborator struct {
	UserID    string
	AppID     string
	Role      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Command struct {
	ID             string
	Name           string
	Description    string
	Enabled        bool
	AppID          string
	ModuleID       pgtype.Text
	CreatorUserID  string
	FlowSource     []byte
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	LastDeployedAt pgtype.Timestamp
}

type Log struct {
	ID        int64
	AppID     string
	Message   string
	Level     string
	CreatedAt pgtype.Timestamp
}

type MessageTemplate struct {
	ID          string
	Name        string
	Description pgtype.Text
	Data        []byte
	FlowSources []byte
	AppID       string
	ModuleID    pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Module struct {
	ID            string
	Name          string
	Description   string
	Enabled       bool
	AppID         string
	CreatorUserID string
	Resources     []byte
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type Session struct {
	KeyHash   string
	UserID    string
	CreatedAt pgtype.Timestamp
	ExpiresAt pgtype.Timestamp
}

type User struct {
	ID              string
	Email           string
	DisplayName     string
	DiscordID       string
	DiscordUsername string
	DiscordAvatar   pgtype.Text
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

type Variable struct {
	ID        string
	Scope     string
	Name      string
	Type      string
	AppID     string
	ModuleID  pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type VariableValue struct {
	ID         int64
	VariableID string
	Scope      pgtype.Text
	Value      []byte
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}
