// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: plugins.sql

package pgmodel

import (
	"context"
)

const getPlugins = `-- name: GetPlugins :many
SELECT id, name, description, created_at, updated_at FROM plugins
`

func (q *Queries) GetPlugins(ctx context.Context) ([]Plugin, error) {
	rows, err := q.db.QueryContext(ctx, getPlugins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plugin
	for rows.Next() {
		var i Plugin
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
