// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resume_points.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createResumePoint = `-- name: CreateResumePoint :exec
INSERT INTO resume_points (
    id, 
    type,
    app_id, 
    command_id, 
    event_listener_id, 
    message_id, 
    message_instance_id,
    flow_source_id, 
    flow_node_id, 
    flow_state, 
    created_at, 
    expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateResumePointParams struct {
	ID                string
	Type              string
	AppID             string
	CommandID         pgtype.Text
	EventListenerID   pgtype.Text
	MessageID         pgtype.Text
	MessageInstanceID pgtype.Int8
	FlowSourceID      pgtype.Text
	FlowNodeID        string
	FlowState         []byte
	CreatedAt         pgtype.Timestamp
	ExpiresAt         pgtype.Timestamp
}

func (q *Queries) CreateResumePoint(ctx context.Context, arg CreateResumePointParams) error {
	_, err := q.db.Exec(ctx, createResumePoint,
		arg.ID,
		arg.Type,
		arg.AppID,
		arg.CommandID,
		arg.EventListenerID,
		arg.MessageID,
		arg.MessageInstanceID,
		arg.FlowSourceID,
		arg.FlowNodeID,
		arg.FlowState,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteResumePoint = `-- name: DeleteResumePoint :exec
DELETE FROM resume_points WHERE id = $1
`

func (q *Queries) DeleteResumePoint(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteResumePoint, id)
	return err
}

const deleteStaleResumePoints = `-- name: DeleteStaleResumePoints :execrows
DELETE FROM resume_points WHERE id IN (
    SELECT stale.id FROM resume_points stale
    WHERE stale.expires_at < $1 OR stale.last_used_at < $2
    LIMIT $3
)
`

type DeleteStaleResumePointsParams struct {
	Now        pgtype.Timestamp
	UsedBefore pgtype.Timestamp
	BatchSize  int32
}

// Batched so a large backlog doesn't hold one long transaction.
func (q *Queries) DeleteStaleResumePoints(ctx context.Context, arg DeleteStaleResumePointsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleResumePoints, arg.Now, arg.UsedBefore, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resumePoint = `-- name: ResumePoint :one
SELECT id, type, app_id, command_id, event_listener_id, message_id, message_instance_id, flow_source_id, flow_node_id, flow_state, created_at, expires_at, last_used_at FROM resume_points WHERE id = $1 AND app_id = $2
`

type ResumePointParams struct {
	ID    string
	AppID string
}

// Scoped by app since the ID comes from a user-controlled custom_id
func (q *Queries) ResumePoint(ctx context.Context, arg ResumePointParams) (ResumePoint, error) {
	row := q.db.QueryRow(ctx, resumePoint, arg.ID, arg.AppID)
	var i ResumePoint
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AppID,
		&i.CommandID,
		&i.EventListenerID,
		&i.MessageID,
		&i.MessageInstanceID,
		&i.FlowSourceID,
		&i.FlowNodeID,
		&i.FlowState,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const touchResumePoint = `-- name: TouchResumePoint :exec
UPDATE resume_points SET last_used_at = $1 WHERE id = $2 AND app_id = $3
`

type TouchResumePointParams struct {
	UsedAt pgtype.Timestamp
	ID     string
	AppID  string
}

func (q *Queries) TouchResumePoint(ctx context.Context, arg TouchResumePointParams) error {
	_, err := q.db.Exec(ctx, touchResumePoint, arg.UsedAt, arg.ID, arg.AppID)
	return err
}
