// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: share_codes.sql
//
// NOTE: this file is hand-written to match sqlc's output style as a
// fallback. Prefer running `sqlc generate` (from kite-service, using the
// existing sqlc.yaml) after adding queries/share_codes.sql and the
// migration — it will regenerate this file (and add the ShareCode struct
// to models.go) for you, and is more reliable than this by-hand version.

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// Add this struct to models.go if you're not running sqlc generate.
// type ShareCode struct {
// 	Code      string
// 	Data      string
// 	CreatedAt pgtype.Timestamp
// }

const createShareCode = `-- name: CreateShareCode :one
INSERT INTO share_codes (code, data, created_at) VALUES ($1, $2, $3) RETURNING code, data, created_at
`

type CreateShareCodeParams struct {
	Code      string
	Data      string
	CreatedAt pgtype.Timestamp
}

func (q *Queries) CreateShareCode(ctx context.Context, arg CreateShareCodeParams) (ShareCode, error) {
	row := q.db.QueryRow(ctx, createShareCode, arg.Code, arg.Data, arg.CreatedAt)
	var i ShareCode
	err := row.Scan(&i.Code, &i.Data, &i.CreatedAt)
	return i, err
}

const getShareCode = `-- name: GetShareCode :one
SELECT code, data, created_at FROM share_codes WHERE code = $1
`

func (q *Queries) GetShareCode(ctx context.Context, code string) (ShareCode, error) {
	row := q.db.QueryRow(ctx, getShareCode, code)
	var i ShareCode
	err := row.Scan(&i.Code, &i.Data, &i.CreatedAt)
	return i, err
}
