// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage_records.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUsageRecord = `-- name: CreateUsageRecord :exec
INSERT INTO usage_records (
    type,
    app_id,
    command_id,
    event_listener_id,
    message_id,
    credits_used,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, type, app_id, command_id, event_listener_id, message_id, credits_used, created_at
`

type CreateUsageRecordParams struct {
	Type            string
	AppID           string
	CommandID       pgtype.Text
	EventListenerID pgtype.Text
	MessageID       pgtype.Text
	CreditsUsed     int32
	CreatedAt       pgtype.Timestamp
}

func (q *Queries) CreateUsageRecord(ctx context.Context, arg CreateUsageRecordParams) error {
	_, err := q.db.Exec(ctx, createUsageRecord,
		arg.Type,
		arg.AppID,
		arg.CommandID,
		arg.EventListenerID,
		arg.MessageID,
		arg.CreditsUsed,
		arg.CreatedAt,
	)
	return err
}

const deleteUsageRecordsBefore = `-- name: DeleteUsageRecordsBefore :execrows
DELETE FROM usage_records WHERE id IN (
    SELECT expired.id FROM usage_records expired
    WHERE expired.created_at < $1
    LIMIT $2
)
`

type DeleteUsageRecordsBeforeParams struct {
	BeforeAt  pgtype.Timestamp
	BatchSize int32
}

// Batched so a large backlog doesn't hold one long transaction.
func (q *Queries) DeleteUsageRecordsBefore(ctx context.Context, arg DeleteUsageRecordsBeforeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUsageRecordsBefore, arg.BeforeAt, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAllUsageCreditsUsedBetween = `-- name: GetAllUsageCreditsUsedBetween :many
SELECT u.app_id, SUM(u.credits_used) FROM usage_records u
JOIN apps a ON a.id = u.app_id AND a.enabled
WHERE u.created_at BETWEEN $1 AND $2
GROUP BY u.app_id
`

type GetAllUsageCreditsUsedBetweenParams struct {
	StartAt pgtype.Timestamp
	EndAt   pgtype.Timestamp
}

type GetAllUsageCreditsUsedBetweenRow struct {
	AppID string
	Sum   int64
}

// Only enabled apps. A disabled app's usage rows stay for the rest of the
// month, so without this filter the credit sweep re-disables it on every run:
// an UPDATE per app per minute, each bumping apps.updated_at, which is the
// cursor GetDisabledAppIDsUpdatedSince feeds to the gateway manager's poll.
func (q *Queries) GetAllUsageCreditsUsedBetween(ctx context.Context, arg GetAllUsageCreditsUsedBetweenParams) ([]GetAllUsageCreditsUsedBetweenRow, error) {
	rows, err := q.db.Query(ctx, getAllUsageCreditsUsedBetween, arg.StartAt, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsageCreditsUsedBetweenRow
	for rows.Next() {
		var i GetAllUsageCreditsUsedBetweenRow
		if err := rows.Scan(&i.AppID, &i.Sum); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageAnalyticsSeriesBetween = `-- name: GetUsageAnalyticsSeriesBetween :many
WITH bounds AS (
    SELECT COALESCE(MAX(date) + 1, '-infinity'::date)::timestamp AS rolled_until FROM usage_daily_rollups
)
SELECT
    s.bucket::timestamp AS bucket,
    s.type::text AS type,
    SUM(s.executions)::bigint AS executions,
    SUM(s.credits_used)::bigint AS credits_used
FROM (
    SELECT date_trunc($1::text, r.date::timestamp) AS bucket, r.type, r.executions, r.credits_used
    FROM usage_daily_rollups r
    WHERE r.app_id = $2 AND r.date::timestamp >= $3::timestamp AND r.date::timestamp < $4::timestamp
    UNION ALL
    SELECT date_trunc($1::text, u.created_at), u.type, 1::bigint, u.credits_used::bigint
    FROM usage_records u, bounds b
    WHERE u.app_id = $2 AND u.created_at >= GREATEST($3::timestamp, b.rolled_until) AND u.created_at < $4::timestamp
) s
GROUP BY 1, 2
ORDER BY 1
`

type GetUsageAnalyticsSeriesBetweenParams struct {
	Bucket  string
	AppID   string
	StartAt pgtype.Timestamp
	EndAt   pgtype.Timestamp
}

type GetUsageAnalyticsSeriesBetweenRow struct {
	Bucket      pgtype.Timestamp
	Type        string
	Executions  int64
	CreditsUsed int64
}

// @bucket is a date_trunc unit: hour, day or month.
func (q *Queries) GetUsageAnalyticsSeriesBetween(ctx context.Context, arg GetUsageAnalyticsSeriesBetweenParams) ([]GetUsageAnalyticsSeriesBetweenRow, error) {
	rows, err := q.db.Query(ctx, getUsageAnalyticsSeriesBetween,
		arg.Bucket,
		arg.AppID,
		arg.StartAt,
		arg.EndAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsageAnalyticsSeriesBetweenRow
	for rows.Next() {
		var i GetUsageAnalyticsSeriesBetweenRow
		if err := rows.Scan(
			&i.Bucket,
			&i.Type,
			&i.Executions,
			&i.CreditsUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageAnalyticsTopSourcesBetween = `-- name: GetUsageAnalyticsTopSourcesBetween :many
WITH bounds AS (
    SELECT COALESCE(MAX(date) + 1, '-infinity'::date)::timestamp AS rolled_until FROM usage_daily_rollups
), totals AS (
    SELECT s.type, s.source_id, SUM(s.executions)::bigint AS executions, SUM(s.credits_used)::bigint AS credits_used
    FROM (
        SELECT r.type, r.source_id, r.executions, r.credits_used
        FROM usage_daily_rollups r
        WHERE r.app_id = $2 AND r.date::timestamp >= $3::timestamp AND r.date::timestamp < $4::timestamp
        UNION ALL
        SELECT u.type, COALESCE(u.command_id, u.event_listener_id, u.message_id, ''), 1::bigint, u.credits_used::bigint
        FROM usage_records u, bounds b
        WHERE u.app_id = $2 AND u.created_at >= GREATEST($3::timestamp, b.rolled_until) AND u.created_at < $4::timestamp
    ) s
    WHERE s.source_id <> ''
    GROUP BY s.type, s.source_id
), ranked AS (
    SELECT t.type, t.source_id, t.executions, t.credits_used, ROW_NUMBER() OVER (PARTITION BY t.type ORDER BY t.executions DESC, t.source_id) AS rank
    FROM totals t
)
SELECT
    ranked.type::text AS type,
    ranked.source_id::text AS source_id,
    ranked.executions::bigint AS executions,
    ranked.credits_used::bigint AS credits_used
FROM ranked
WHERE ranked.rank <= $1::int
ORDER BY ranked.type, ranked.executions DESC, ranked.source_id
`

type GetUsageAnalyticsTopSourcesBetweenParams struct {
	PerType int32
	AppID   string
	StartAt pgtype.Timestamp
	EndAt   pgtype.Timestamp
}

type GetUsageAnalyticsTopSourcesBetweenRow struct {
	Type        string
	SourceID    string
	Executions  int64
	CreditsUsed int64
}

// Returns up to @per_type sources for each type, most executions first.
func (q *Queries) GetUsageAnalyticsTopSourcesBetween(ctx context.Context, arg GetUsageAnalyticsTopSourcesBetweenParams) ([]GetUsageAnalyticsTopSourcesBetweenRow, error) {
	rows, err := q.db.Query(ctx, getUsageAnalyticsTopSourcesBetween,
		arg.PerType,
		arg.AppID,
		arg.StartAt,
		arg.EndAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsageAnalyticsTopSourcesBetweenRow
	for rows.Next() {
		var i GetUsageAnalyticsTopSourcesBetweenRow
		if err := rows.Scan(
			&i.Type,
			&i.SourceID,
			&i.Executions,
			&i.CreditsUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageAnalyticsTotalsBetween = `-- name: GetUsageAnalyticsTotalsBetween :many
WITH bounds AS (
    SELECT COALESCE(MAX(date) + 1, '-infinity'::date)::timestamp AS rolled_until FROM usage_daily_rollups
)
SELECT
    s.type::text AS type,
    SUM(s.executions)::bigint AS executions,
    SUM(s.credits_used)::bigint AS credits_used
FROM (
    SELECT r.type, r.executions, r.credits_used
    FROM usage_daily_rollups r
    WHERE r.app_id = $1 AND r.date::timestamp >= $2::timestamp AND r.date::timestamp < $3::timestamp
    UNION ALL
    SELECT u.type, 1::bigint, u.credits_used::bigint
    FROM usage_records u, bounds b
    WHERE u.app_id = $1 AND u.created_at >= GREATEST($2::timestamp, b.rolled_until) AND u.created_at < $3::timestamp
) s
GROUP BY s.type
`

type GetUsageAnalyticsTotalsBetweenParams struct {
	AppID   string
	StartAt pgtype.Timestamp
	EndAt   pgtype.Timestamp
}

type GetUsageAnalyticsTotalsBetweenRow struct {
	Type        string
	Executions  int64
	CreditsUsed int64
}

// The analytics queries read rolled up days from usage_daily_rollups and the
// rest from usage_records. Records of rolled up days that the cleanup hasn't
// deleted yet are skipped so nothing is counted twice.
func (q *Queries) GetUsageAnalyticsTotalsBetween(ctx context.Context, arg GetUsageAnalyticsTotalsBetweenParams) ([]GetUsageAnalyticsTotalsBetweenRow, error) {
	rows, err := q.db.Query(ctx, getUsageAnalyticsTotalsBetween, arg.AppID, arg.StartAt, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsageAnalyticsTotalsBetweenRow
	for rows.Next() {
		var i GetUsageAnalyticsTotalsBetweenRow
		if err := rows.Scan(&i.Type, &i.Executions, &i.CreditsUsed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageCreditsUsedByAppBetween = `-- name: GetUsageCreditsUsedByAppBetween :one
SELECT COALESCE(SUM(credits_used), 0)::int FROM usage_records WHERE app_id = $1 AND created_at BETWEEN $2 AND $3
`

type GetUsageCreditsUsedByAppBetweenParams struct {
	AppID   string
	StartAt pgtype.Timestamp
	EndAt   pgtype.Timestamp
}

func (q *Queries) GetUsageCreditsUsedByAppBetween(ctx context.Context, arg GetUsageCreditsUsedByAppBetweenParams) (int32, error) {
	row := q.db.QueryRow(ctx, getUsageCreditsUsedByAppBetween, arg.AppID, arg.StartAt, arg.EndAt)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getUsageCreditsUsedByDayBetween = `-- name: GetUsageCreditsUsedByDayBetween :many
SELECT 
    d.dt as date, 
    coalesce(u.credits_used, 0) as credits_used 
FROM (
    SELECT dt::date 
    FROM generate_series($1::timestamp, $2::timestamp, '1 day'::interval) dt
) d
LEFT JOIN (
    SELECT DATE(created_at) as date, SUM(credits_used) as credits_used 
    FROM usage_records 
    WHERE app_id = $3 AND created_at BETWEEN $1 AND $2 
    GROUP BY DATE(created_at)
) u ON d.dt = u.date
ORDER BY d.dt
`

type GetUsageCreditsUsedByDayBetweenParams struct {
	StartAt pgtype.Timestamp
	EndAt   pgtype.Timestamp
	AppID   string
}

type GetUsageCreditsUsedByDayBetweenRow struct {
	Date        pgtype.Date
	CreditsUsed int64
}

func (q *Queries) GetUsageCreditsUsedByDayBetween(ctx context.Context, arg GetUsageCreditsUsedByDayBetweenParams) ([]GetUsageCreditsUsedByDayBetweenRow, error) {
	rows, err := q.db.Query(ctx, getUsageCreditsUsedByDayBetween, arg.StartAt, arg.EndAt, arg.AppID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsageCreditsUsedByDayBetweenRow
	for rows.Next() {
		var i GetUsageCreditsUsedByDayBetweenRow
		if err := rows.Scan(&i.Date, &i.CreditsUsed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageCreditsUsedByTypeBetween = `-- name: GetUsageCreditsUsedByTypeBetween :many
SELECT type, SUM(credits_used) FROM usage_records WHERE app_id = $1 AND created_at BETWEEN $2 AND $3 GROUP BY type
`

type GetUsageCreditsUsedByTypeBetweenParams struct {
	AppID   string
	StartAt pgtype.Timestamp
	EndAt   pgtype.Timestamp
}

type GetUsageCreditsUsedByTypeBetweenRow struct {
	Type string
	Sum  int64
}

func (q *Queries) GetUsageCreditsUsedByTypeBetween(ctx context.Context, arg GetUsageCreditsUsedByTypeBetweenParams) ([]GetUsageCreditsUsedByTypeBetweenRow, error) {
	rows, err := q.db.Query(ctx, getUsageCreditsUsedByTypeBetween, arg.AppID, arg.StartAt, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsageCreditsUsedByTypeBetweenRow
	for rows.Next() {
		var i GetUsageCreditsUsedByTypeBetweenRow
		if err := rows.Scan(&i.Type, &i.Sum); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageRecordsByAppBetween = `-- name: GetUsageRecordsByAppBetween :many
SELECT id, type, app_id, command_id, event_listener_id, message_id, credits_used, created_at FROM usage_records WHERE app_id = $1 AND created_at BETWEEN $2 AND $3 ORDER BY created_at DESC
`

type GetUsageRecordsByAppBetweenParams struct {
	AppID   string
	StartAt pgtype.Timestamp
	EndAt   pgtype.Timestamp
}

func (q *Queries) GetUsageRecordsByAppBetween(ctx context.Context, arg GetUsageRecordsByAppBetweenParams) ([]UsageRecord, error) {
	rows, err := q.db.Query(ctx, getUsageRecordsByAppBetween, arg.AppID, arg.StartAt, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageRecord
	for rows.Next() {
		var i UsageRecord
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.AppID,
			&i.CommandID,
			&i.EventListenerID,
			&i.MessageID,
			&i.CreditsUsed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollupUsageRecordsBefore = `-- name: RollupUsageRecordsBefore :execrows
INSERT INTO usage_daily_rollups (date, app_id, type, source_id, executions, credits_used)
SELECT
    DATE(u.created_at),
    u.app_id,
    u.type,
    COALESCE(u.command_id, u.event_listener_id, u.message_id, ''),
    COUNT(*),
    SUM(u.credits_used)
FROM usage_records u
WHERE u.created_at < $1::timestamp
    AND u.created_at >= (SELECT COALESCE(MAX(r.date) + 1, '-infinity'::date)::timestamp FROM usage_daily_rollups r)
GROUP BY 1, 2, 3, 4
ON CONFLICT DO NOTHING
`

// Sums every whole day before @before_at that isn't rolled up yet into
// usage_daily_rollups. Days are rolled up in order, so everything before the
// latest rolled up day is already done. @before_at must be midnight UTC.
func (q *Queries) RollupUsageRecordsBefore(ctx context.Context, beforeAt pgtype.Timestamp) (int64, error) {
	result, err := q.db.Exec(ctx, rollupUsageRecordsBefore, beforeAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
