#!/usr/bin/env bash
# Generates the nginx config and the systemd unit of the service clusters from
# deploy/config.env. Commit the result and apply it with deploy/server.sh.
set -euo pipefail

DEPLOY="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$DEPLOY/config.env"

# split_clients works in steps of 0.01%, util.CluserForKey splits the hash space
# into equal ranges. They only agree when every share is a whole number of steps.
if ((CLUSTER_COUNT < 1 || 10000 % CLUSTER_COUNT != 0)); then
  echo "CLUSTER_COUNT must divide 10000 (1, 2, 4, 5, 8, 10, 16, 20, 25, ...), got $CLUSTER_COUNT." >&2
  exit 1
fi

share=$((10000 / CLUSTER_COUNT))
upstreams=""
shares=""
clusters=""
for ((i = 0; i < CLUSTER_COUNT; i++)); do
  upstreams+="upstream kite_cluster_$i { server 127.0.0.1:$((SERVICE_BASE_PORT + i)); }"$'\n'
  if ((i < CLUSTER_COUNT - 1)); then
    if ((share % 100 == 0)); then
      shares+="        $((share / 100))% \"$i\";"$'\n'
    else
      shares+="$(printf '        %d.%02d%% "%d";' $((share / 100)) $((share % 100)) "$i")"$'\n'
    fi
  else
    shares+="        * \"$i\";"$'\n'
  fi
  clusters+="        \"$i\" kite_cluster_$i;"$'\n'
done

render() {
  local out="$1"
  out="${out//@CLUSTER_COUNT@/$CLUSTER_COUNT}"
  out="${out//@SERVICE_BASE_PORT@/$SERVICE_BASE_PORT}"
  out="${out//@SERVICE_DIR@/$SERVICE_DIR}"
  out="${out//@WEB_DOMAIN@/$WEB_DOMAIN}"
  out="${out//@DOCS_DOMAIN@/$DOCS_DOMAIN}"
  out="${out//@API_DOMAIN@/$API_DOMAIN}"
  out="${out//@WEB_DIR@/$WEB_DIR}"
  out="${out//@DOCS_DIR@/$DOCS_DIR}"
  out="${out//@API_MAX_BODY_SIZE@/$API_MAX_BODY_SIZE}"
  out="${out//@UPSTREAMS@/${upstreams%$'\n'}}"
  out="${out//@SHARES@/${shares%$'\n'}}"
  out="${out//@CLUSTERS@/${clusters%$'\n'}}"
  printf '%s\n' "$out"
}

read -r -d '' nginx_template <<'EOF' || true
# Generated by deploy/generate.sh from deploy/config.env, don't edit.
#
# nginx config for @WEB_DOMAIN@, @DOCS_DOMAIN@ and @API_DOMAIN@, included inside
# the http block. All traffic arrives through the Cloudflare tunnel, which
# connects from localhost.

# Use the client IP from Cloudflare. Only the tunnel can reach nginx, so the
# header can be trusted.
set_real_ip_from 127.0.0.1;
set_real_ip_from ::1;
real_ip_header CF-Connecting-IP;

# Rate limits per client IP, with a stricter one for writes. CORS preflights
# only count towards the general limit, otherwise every write counts twice.
map $request_method $kite_api_write_key {
        default $binary_remote_addr;
        GET     "";
        HEAD    "";
        OPTIONS "";
}

limit_req_zone $binary_remote_addr zone=kite_api:64m rate=10r/s;
limit_req_zone $kite_api_write_key zone=kite_api_write:64m rate=2r/s;
limit_req_status 429;

# One upstream per service cluster. Requests for an app go to the cluster that
# runs it, split_clients hashes the same way as util.CluserForKey.
@UPSTREAMS@

map $uri $kite_app_id {
        ~^/v1/apps/(?<id>[^/]+)/ $id;
        default "";
}

split_clients "${kite_app_id}" $kite_cluster {
@SHARES@
}

map $kite_cluster $kite_upstream {
        default kite_cluster_0; # requests that aren't for an app
@CLUSTERS@
}

map $http_upgrade $kite_connection_upgrade {
        default upgrade;
        ""      "";
}

server {
        listen 127.0.0.1:80 default_server;
        server_name @API_DOMAIN@;

        location / {
                limit_req zone=kite_api burst=50 delay=10;
                limit_req zone=kite_api_write burst=5;

                proxy_pass http://$kite_upstream;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $kite_connection_upgrade;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Real-IP $remote_addr;

                client_max_body_size @API_MAX_BODY_SIZE@;
                proxy_connect_timeout 60s;
                proxy_read_timeout 60s;
                proxy_send_timeout 60s;
                send_timeout 60s;
        }
}

server {
        listen 127.0.0.1:80;
        server_name www.@WEB_DOMAIN@;

        return 308 https://@WEB_DOMAIN@$request_uri;
}

server {
        listen 127.0.0.1:80;
        server_name @WEB_DOMAIN@;

        root @WEB_DIR@;
        absolute_redirect off;

        location /_next/static/ {
                add_header Cache-Control "public, max-age=31536000, immutable";
        }

        # Written by kite-web/scripts/export-node-info.ts, read by the docs.
        location ~ ^/api/flow/nodes/([^/]+)$ {
                add_header Access-Control-Allow-Origin https://@DOCS_DOMAIN@;
                default_type application/json;
                try_files /api/flow/nodes/$1.json =404;
        }

        # The export writes dynamic routes to literal files like apps/[appId].html.
        location ~ ^/apps/[^/]+/?$ {
                try_files "/apps/[appId].html" =404;
        }
        location ~ ^/apps/[^/]+/commands/[^/]+/?$ {
                try_files "/apps/[appId]/commands/[cmdId].html" =404;
        }
        location ~ ^/apps/[^/]+/events/[^/]+/?$ {
                try_files "/apps/[appId]/events/[eventId].html" =404;
        }
        location ~ ^/apps/[^/]+/messages/[^/]+/?$ {
                try_files "/apps/[appId]/messages/[messageId].html" =404;
        }
        location ~ ^/apps/[^/]+/variables/[^/]+/?$ {
                try_files "/apps/[appId]/variables/[variableId].html" =404;
        }
        location ~ ^/apps/[^/]+/([^/]+)/?$ {
                try_files "/apps/[appId]/$1.html" =404;
        }

        location / {
                try_files $uri $uri.html $uri/ =404;
        }

        error_page 404 /404.html;
}

server {
        listen 127.0.0.1:80;
        server_name @DOCS_DOMAIN@;

        root @DOCS_DIR@;
        absolute_redirect off;

        location / {
                try_files $uri $uri/ $uri.html =404;
        }

        error_page 404 /404.html;
}
EOF
render "$nginx_template" >"$DEPLOY/nginx.conf"

# systemd expands $ itself, so the port arithmetic for the shell needs $$.
read -r -d '' unit_template <<'EOF' || true
# Generated by deploy/generate.sh from deploy/config.env, don't edit.
#
# Service cluster %i of @CLUSTER_COUNT@, run as kite-service@0 to kite-service@N.
# Reads kite.toml from @SERVICE_DIR@ and applies migrations on every start.
[Unit]
Description=Kite cluster %i
After=network-online.target postgresql.service
Wants=network-online.target
StartLimitIntervalSec=0

[Service]
WorkingDirectory=@SERVICE_DIR@
ExecStartPre=@SERVICE_DIR@/kite-service database migrate postgres up
ExecStart=/bin/sh -c 'exec @SERVICE_DIR@/kite-service server start --cluster_count @CLUSTER_COUNT@ --cluster_index %i --port $$((@SERVICE_BASE_PORT@ + %i))'
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
render "$unit_template" >"$DEPLOY/kite-service@.service"

echo "Generated deploy/nginx.conf and deploy/kite-service@.service for $CLUSTER_COUNT clusters."
