// Code generated by tygo. DO NOT EDIT.

//////////
// source: call.go

export interface KVKeyGetCall {
  namespace: string;
  key: string;
}
export type KVKeyGetResponse = TypedKVValue;
export interface KVKeySetCall {
  namespace: string;
  key: string;
  value: TypedKVValue;
}
export interface KVKeySetResponse {
}
export interface KVKeyDeleteCall {
  namespace: string;
  key: string;
}
export type KVKeyDeleteResponse = TypedKVValue;
export interface KVKeyIncreaseCall {
  namespace: string;
  key: string;
  increment: number /* int */;
}
export type KVKeyIncreaseResponse = TypedKVValue;

//////////
// source: value.go

export type KVValueType = string;
export const KVValueTypeString: KVValueType = "STRING";
export const KVValueTypeInt: KVValueType = "INT";
export interface TypedKVValue {
  type: KVValueType;
  value: KVValue;
}
export type KVValue = any;
export type KVString = string;
export type KVInt = number /* int */;
